version: "3.1"
services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: weblazy_service
    working_dir: /var/www/html
    ports:
      - "9021:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - mysql
  mysql:
    image: mysql:5.6
    container_name: weblazy_mysql
    ports:
      - "9022:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: webLazy
      MYSQL_USER: vuongkma
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin
    container_name: weblazy__phpmyadmin
    depends_on:
      - mysql
    ports:
      - "9023:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
